<?php
    $dbhost="localhost";
    $dbname="***";
    $dbuser="***";
    $dbpassword="***";
?>
<!-- 
<!?php
    $dbhost="localhost";
    $dbname="my_vdftutorial";
    $dbsuer="vdftutorial";
    $dbpassword="";
?-->
